/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'mati' at '11/02/16 8:29' with Gradle 2.6
 *
 * @author mati, @date 11/02/16 8:29
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
