/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'mati' at '17/12/15 8:12' with Gradle 2.6
 *
 * @author mati, @date 17/12/15 8:12
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
